### PR TITLE
Landing page created

### PR DESCRIPTION
**Pull request by msdeshmukh009**

### CODE REVIEW

**Review by Shrinkhlarajpoot — APPROVED** [review]

**Comment by vijaytembugade** [comment]
You can add pics or screenshots of landing page in PR so that we can see .

**Comment by msdeshmukh009** [comment]
> You can add pics or screenshots of landing page in PR so that we can see .

For a preview, you can add "box" in URL right after the github like this https://githubbox.com/msdeshmukh009/orion-ui/tree/landing-page and it will open in codesandbox , please review this.

**Comment by MarkVed17** [comment]
The page looks clean yet so elegant. Just that I really miss the hover on the link & button 😅

**Review by vijaytembugade — APPROVED** [review]
Great color and styles.
Fonts are also amazing.

**Comment by msdeshmukh009** [comment]
> The page looks clean yet so elegant. Just that I really miss the hover on the link & button 😅

I have decreased opacity on hover but I think I will try other options, thanks for the suggestions.😄

**Pull request merged**
